Feature/95 last move visible
nclskfm/dhbw-studienarbeit-muehle pull request #105
Opened 2021-02-25 09:44 UTC by nclskfm

closes #95 

hab auch noch die farbe vom schwarzen spieler ein bisschen aufgehellt.

![image](https://user-images.githubusercontent.com/52164046/109134155-0b92e080-7756-11eb-8226-adbc560e6a50.png)

![image](https://user-images.githubusercontent.com/52164046/109134224-1c435680-7756-11eb-989c-96061419f506.png)

2021-02-25 10:28 UTC, jstsddg requested changes

2021-02-25 10:28 UTC, jstsddg commented on jupyter/nmm-gui.ipynb
> +    "- `selected` ist ein optionaler Booleanwert, der angibt, ob ein Spielerstein ausgewählt ist oder nicht. Der Standardwert ist `False`;\n",
Heißt es nicht `ein boolischer Wert`?

2021-02-25 10:28 UTC, jstsddg commented on jupyter/nmm-gui.ipynb
> +    "- `lastMoved` ist ein optionaler Booleanwert, der angibt ob der zu zeichende Spielerstein zuletzt bewegt worden ist. Der Standardwert ist `False`."
`zu zeichnende`

2021-02-25 10:28 UTC, jstsddg commented on jupyter/nmm-gui.ipynb
> +    "- `oldtState` ist der Ausgangszustand;\n",
Typo in variable

2021-02-25 10:29 UTC, jstsddg commented
Können gelöschte Steine angezeigt werden?

2021-02-25 10:32 UTC, nclskfm commented
> Können gelöschte Steine angezeigt werden?

Wie meinst du? Auf dem Board oder ein Friedhof (also wie der Stash)? ^^

2021-02-25 10:46 UTC, jstsddg commented
Ich meinte auf dem Board, dass man sehen kann, wo der Gegner Steine weg genommen hat. Ich weiß nicht in wie fern das gefordert ist, war erstmal nur so eine Überlegung.

2021-02-25 10:48 UTC, nclskfm commented
hmm, umsetzbar wäre es auf jeden Fall, hast du eine Idee, wie man das darstellen könnte?

2021-02-27 12:53 UTC, jstsddg approved these changes

2021-02-27 12:54 UTC, merged