#130: better explanation of iterative deepening
nclskfm/dhbw-studienarbeit-muehle pull request #172
Opened 2021-04-26 14:08 UTC by benfu99

closes #130

2021-04-29 14:29 UTC, benfu99 commented
ping @nclskfm @js

2021-04-30 12:59 UTC, jstsddg requested changes

2021-04-30 12:59 UTC, jstsddg commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "Dies sorgt gerade in Phase 3 des Mühle-Spiels dafür, dass die Spielzüge um einiges weiter im Voraus berechnet werden können.\n",
```suggestion
    "Dies sorgt gerade in Phase 2 des Mühle-Spiels dafür, dass die Spielzüge um einiges weiter im Voraus berechnet werden können.\n",
```

2021-04-30 12:59 UTC, jstsddg commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "Dieses bietet den Vorteil gegenüber fest definierten Tiefenlimits, dass bei weniger komplexen Bäumen die Suche weiter fortgesetzt werden kann und die Antwortzeit an den Nutzer durch die gleiche
```suggestion
    "Dieses bietet den Vorteil gegenüber fest definierten Tiefenlimits, dass bei weniger komplexen Bäumen die Suche weiter fortgesetzt werden kann und die Antwortzeit an den Nutzer durch die gleiche Anzahl an Zuständen nahezu konstant bleibt.\n",
```

2021-04-30 12:59 UTC, jstsddg commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "In der Umsetzung bedeutet das, dass das Limit bei einem Aufruf der `bestMoves()`-Funktion das Limit zunächst immer auf 1 gesetzt ist. Wenn nach der Betrachung aller Zustände in diesem limit noch
```suggestion
    "In der Umsetzung bedeutet das, dass die maximale Rekursionstiefe bei einem Aufruf der `bestMoves()`-Funktion zunächst immer bei `limit=1` liegt. Wenn nach der Betrachung aller Zustände mit Verwendung der Rekursionstiefe noch keine `IterativeMaxCountException()` geworfen wurde, wird das Maximum um eins erhöht.\n",
```
Hier darfst du das auch gerne etwas anders schreiben. Aber sonst haben wir es glaube ich immer *maximale Rekursionstiefe* genannt.

2021-04-30 12:59 UTC, jstsddg commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "Die gewünschte maximale Anzahl an Zuständen `maxCount` kann in der GUI definiert werden.\n",
```suggestion
    "Die gewünschte maximale Anzahl an Zuständen `maxCount` kann im `AlphaBetaPruning`-Konstruktor mit Hilfe der Option `max_states` festgelegt werden.\n",
```

2021-04-30 13:38 UTC, jstsddg approved these changes

2021-04-30 21:56 UTC, merged