#182: implement 3 3
nclskfm/dhbw-studienarbeit-muehle pull request #191
Opened 2021-06-08 08:40 UTC by benfu99

closes #182

2021-06-10 07:24 UTC, jstsddg commented on jupyter/nmm-retro.ipynb
> +    "    stones = tuple([0, 0])\n",
```python
assert tuple([1, 2]) == (1,2)
```

2021-06-11 12:18 UTC, nclskfm requested changes

2021-06-11 12:18 UTC, nclskfm commented on jupyter/nmm-retro.ipynb
> +    "Die Enspieldatenbank soll alle Zustände speichern in denen der weiße Spieler auf jeden Fall gewinnt. Dafür ist es notwendig zunächst alle möglichen Spielfelder mit drei weißen und drei schwarzen
```suggestion
    "Die Endspieldatenbank soll alle Zustände speichern, in denen der weiße Spieler auf jeden Fall gewinnt. Dafür ist es notwendig, zunächst alle möglichen Spielfelder mit drei weißen und drei schwarzen Spielsteinen zu generieren, um im Nachhinein untersuchen zu können, ob diese zu den Gewinnzuständen gehören.\n",
```

2021-06-11 12:18 UTC, nclskfm commented on jupyter/nmm-retro.ipynb
> +    "Da es nicht ausgeschlossen werden kann, dass zwei Steine auf die selbe Position gesetzt werden und somit nicht die gewünschte 3-3-Kombination vorhanden ist, wird vor dem speichern der Spielbrett
```suggestion
    "Da es nicht ausgeschlossen werden kann, dass zwei Steine auf die selbe Position gesetzt werden und somit nicht die gewünschte 3-3-Kombination vorhanden ist, wird vor dem Speichern der Spielbretter überprüft, ob für beide Farben drei Steine platziert wurden.\n",
```

2021-06-11 12:18 UTC, nclskfm commented on jupyter/nmm-retro.ipynb
> +    "Die Entscheidung, die Spielbretter global abzuspeichern wurde bewusst getroffen, um bei Änderungen an anderen Funktionen nicht die Generierung der Spielbretter neu starten zu müssen, welche eini
Vielleicht noch anmerken, was a1 bis f2 darstellen? (oder wie variablen umbennen :D)

2021-06-11 12:18 UTC, nclskfm commented on jupyter/nmm-retro.ipynb
> +    "Die Funktion `getSymmetryUnique(boards)` iteriert über jedes Spielfeld und erhält von der `getUniqueStateForSymmetry(state)` das Spielfeld, welches unter allen Symmetrien das niedrigste `weight`
```suggestion
    "Die Funktion `getSymmetryUnique(boards)` iteriert über jedes Spielfeld und erhält von der `getUniqueStateForSymmetry(state)` das Spielfeld, welches unter allen Symmetrien die niedrigste Gewichtung (`weight`) aufweist und fügt dieses den `uniqueStates` hinzu. So wird sichergestellt, das für alle Symmetrien nur ein Repräsentant abgespeichert wird."
```

2021-06-11 13:21 UTC, benfu99 commented on jupyter/nmm-retro.ipynb
> +    "Die Entscheidung, die Spielbretter global abzuspeichern wurde bewusst getroffen, um bei Änderungen an anderen Funktionen nicht die Generierung der Spielbretter neu starten zu müssen, welche eini
ist umbenannt :)

2021-06-11 13:21 UTC, nclskfm approved these changes

2021-06-11 13:22 UTC, merged