#218 Explained strange default value in AlphaBeta (pickle, multiprocessing)
nclskfm/dhbw-studienarbeit-muehle pull request #230
Opened 2021-06-25 12:40 UTC by jstsddg

Closes #218

2021-06-25 13:22 UTC, benfu99 requested changes
Typos

2021-06-25 13:22 UTC, benfu99 commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "2. Läde man darauf hin das `Minimax` Notebook, dann lädt dieses die `HeuristicWeights` Klasse erneut. Dabei wird jedoch eine neue Klasse unter dem gleichen Namen, aber an einem anderen Ort im Ar
```suggestion
    "2. Lüde man darauf hin das `Minimax` Notebook, dann lädt dieses die `HeuristicWeights` Klasse erneut. Dabei wird jedoch eine neue Klasse unter dem gleichen Namen, aber an einem anderen Ort im Arbeitsspeicher angelegt.\n",
```
Also richtig wäre im Konjunktiv 2 "Lüde". Aber willst du wirklich hier den Konjunktiv 2 verwenden? xD

2021-06-25 13:22 UTC, benfu99 commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "3. Wird nun ebenso der Standardwert des `weights` Parameters im `Minimax` Algorithmus beim ersten Laden gesetzt, dann teilen sich zwar beide Standardwerte die gleiche Implementierung der `Heuris
```suggestion
    "3. Wird nun ebenso der Standardwert des `weights` Parameters im `Minimax` Algorithmus beim ersten Laden gesetzt, dann teilen sich zwar beide Standardwerte die gleiche Implementierung der `HeuristikWeights` Klasse, zeigen jedoch auf verschiedene Adressen im Arbeitsspeicher.\n",
```

2021-06-25 13:22 UTC, benfu99 commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "4. Dies wird zum Problem, wenn die Objekte mit Hilfe des `pickel` Paketes serialisiert werden, damit sie im `multiprocessing` Paket über die Threadgrenzen gesendet werden können. Hier wird ein F
```suggestion
    "4. Dies wird zum Problem, wenn die Objekte mit Hilfe des `pickel` Paketes serialisiert werden, damit sie im `multiprocessing` Paket über die Threadgrenzen gesendet werden können. Hier wird ein Fehler ausgelöst, wenn der Name der Klassen übereinstimmt, jedoch auf verschiedene Adressen im Speicher verwiesen wird."
```

2021-06-25 16:01 UTC, jstsddg commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "2. Läde man darauf hin das `Minimax` Notebook, dann lädt dieses die `HeuristicWeights` Klasse erneut. Dabei wird jedoch eine neue Klasse unter dem gleichen Namen, aber an einem anderen Ort im Ar
Ahhh, ich wollte eigentlich "Läd" schreiben :D "Lüde" hätte aber auch Stil :P

2021-06-26 20:08 UTC, nclskfm approved these changes
Ein typo

2021-06-26 20:08 UTC, nclskfm commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "2. Läd man darauf hin das `Minimax` Notebook, dann lädt dieses die `HeuristicWeights` Klasse erneut. Dabei wird jedoch eine neue Klasse unter dem gleichen Namen, aber an einem anderen Ort im Arb
```suggestion
    "2. Lädt man darauf hin das `Minimax` Notebook, dann lädt dieses die `HeuristicWeights` Klasse erneut. Dabei wird jedoch eine neue Klasse unter dem gleichen Namen, aber an einem anderen Ort im Arbeitsspeicher angelegt.\n",
```

2021-06-28 06:50 UTC, merged