#18 and #19 Implemented Alpha-Beta-Pruning
nclskfm/dhbw-studienarbeit-muehle pull request #84
Opened 2021-02-07 00:27 UTC by jstsddg

* Implementierung von Alpha-Beta-Pruning
* Verschieben der Heuristik in ein eigenes Notebook
* Setzen der Maximalen Rekursionstiefe in Minimax via `limit` (wie im Skript)
* Verwendung einer gleichen Maximierungsfunktion in Minimax und Alpha-Beta-Pruning

Closes #18
Closes #19

2021-02-07 10:38 UTC, nclskfm requested changes
eine kleine anmerkung. Und den Bug in playerphaseThree noch fixen bitte.

@benfu99 sollte aber auch nochmal rüberschauen - hab nicht so viel Ahnung über alphaBeta pruning :)

2021-02-07 10:38 UTC, nclskfm commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "def value(s, p, limit, alpha=-1, beta=1):\n",
Bei minimax gibt es auch die Funktion `value`. Es ist zwar kein Problem, aber der Verständlichkeit würde ich die Funktion eindeutig benennen. Also zum Beispiel `ǘalueAlphaBeta` (so wie du es bei bestMove gemacht hast - da musstest du es ja auch machen xD).

Und die Funktionen vom minimax-Algorithmus würde ich auch umbenennen und überall ein `Minimax` ranhängen

2021-02-07 18:30 UTC, jstsddg commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "def value(s, p, limit, alpha=-1, beta=1):\n",
Geändert ;)

2021-02-07 18:30 UTC, jstsddg commented
@nclskfm Neues Review bitte <3

2021-02-08 09:17 UTC, nclskfm approved these changes
jetzt haben wir überall camelcase und hier snake case xD

2021-02-08 09:30 UTC, benfu99 requested changes
Ich glaube ich fände es besser, wenn wir ab sofort das was mit gemacht haben direkt mit der entsprechenden Doku versehen. Dann sind wir gezwungen es direkt mit zu machen und fragen uns nicht 5 Tage später, wie wir es gemacht haben

2021-02-08 11:48 UTC, benfu99 approved these changes
Bis auf den einen Grammatikfehler fein :)

2021-02-08 11:48 UTC, benfu99 commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "Die `value_AB()` Funktion ist ein Wrapper für die eigentliche Implementierung des α-β-Pruning in der Funktion `alphaBeta()`. Dieser Wrapper stellt Caching der Ergebnisse zur Verfügung, bzw. bere
Grammatik im letzten Satz

2021-02-08 14:03 UTC, jstsddg commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "Die `value_AB()` Funktion ist ein Wrapper für die eigentliche Implementierung des α-β-Pruning in der Funktion `alphaBeta()`. Dieser Wrapper stellt Caching der Ergebnisse zur Verfügung, bzw. bere
Gefixt :) Ich merge dann

2021-02-08 14:03 UTC, merged