Added profiling and performance improvements
nclskfm/dhbw-studienarbeit-muehle pull request #89
Opened 2021-02-08 22:57 UTC by jstsddg

Im ersten Ergebnis des Profilers wurde ersichtlich, dass die `heuristic()` Funktion die meiste Rechenzeit verbraucht:
```
Total time: 37.2156 s
File: &lt;ipython-input-4-0cd11c88766d&gt;
Function: alphaBeta at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     1                                           def alphaBeta(s, p, limit, alpha, beta):
     2      3121    9464692.0   3032.6     25.4      if finished(s, p):
     3                                                   return utility(s, p)
     4      3121       2525.0      0.8      0.0      if limit == 0:
     5      2545   25913574.0  10182.2     69.6          return heuristic(s, p)
     6       576        337.0      0.6      0.0      val = alpha
     7      3753    1806906.0    481.5      4.9      for ns in nextStates(s, p):
     8      3705      16419.0      4.4      0.0          val = max(val, -value_AB(ns, opponent(p), limit-1, -beta, -alpha))
     9      3705       3671.0      1.0      0.0          if val &gt;= beta:
    10       528       3234.0      6.1      0.0              return val
    11      3177       4161.0      1.3      0.0          alpha = max(val, alpha)
    12        48         31.0      0.6      0.0      return val
```

In dieser Methode benötigt die `nextStates()` Funktion die meiste Rechenzeit:
```
Total time: 25.8639 s
File: &lt;ipython-input-2-4527128f0c7a&gt;
Function: heuristic at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     1                                           def heuristic(s, p):
     2      2545       6043.0      2.4      0.0      op = opponent(p)
     3      2545       3578.0      1.4      0.0      (_, board) = s
     4                                               # finding possible mills in next states
     5      2545   12604216.0   4952.5     48.7      pPossMills = sum(len(findMills(nB, p)) for (_, nB) in nextStates(s, p))
     6      2545   12702165.0   4991.0     49.1      opPossMills = sum(len(findMills(nB, op)) for (_, nB) in nextStates(s, op))
     7                                               # adding all score parameters
     8      2545     266585.0    104.7      1.0      pScore = countStones(s, p) + len(findMills(board, p)) * 4 + pPossMills * 2
     9      2545     267016.0    104.9      1.0      opScore = countStones(s, op) + len(findMills(board, op)) * 4 + opPossMills * 2
    10                                               # subtracting opponent score from own players score
    11      2545       3869.0      1.5      0.0      result = pScore - opScore
    12                                               # limeting the score to not overwrite real value score
    13      2545       3310.0      1.3      0.0      if result &gt; 90:
    14                                                   result = 90
    15      2545       3416.0      1.3      0.0      if result &lt; -90:
    16                                                   result = -90
    17      2545       3667.0      1.4      0.0      return result / 100
```

Deswegen habe ich die Berechnung der möglichen Mühlen entfernt. Dadurch wird zwar die Genauigkeit der Heuristik geringer, allerdings wird der Algorithmus um einen Faktor > 2 schneller, wodurch das Rekursionslimit um 1 erhöht werden konnte. Dies dürfte sogar kein Null-Summen-Spiel sein, sondern die Genauigkeit insgesamt erhöhen, da nun im nächsten Schritt auch der Check auf `finished()` und die `heuristic()` auf alle folgenden States angewandt werden kann.

Des Weiteren war es möglich innerhalb der `alphaBeta()` Funktion die `nextStates()` für die `finished()` Funktion und die Schleife zuwischen zu speichern. Vorher:
```
Total time: 37.7564 s
File: &lt;ipython-input-4-0cd11c88766d&gt;
Function: alphaBeta at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     1                                           def alphaBeta(s, p, limit, alpha, beta):
     2     10442   31232813.0   2991.1     82.7      if finished(s, p):
     3                                                   return utility(s, p)
     4     10442       7903.0      0.8      0.0      if limit == 0:
     5      8946    1972773.0    220.5      5.2          return heuristic(s, p)
     6      1496        987.0      0.7      0.0      val = alpha
     7     11585    4471692.0    386.0     11.8      for ns in nextStates(s, p):
     8     11108      39327.0      3.5      0.1          val = max(val, -value_AB(ns, opponent(p), limit-1, -beta, -alpha))
     9     11108      11131.0      1.0      0.0          if val &gt;= beta:
    10      1019       6845.0      6.7      0.0              return val
    11     10089      12603.0      1.2      0.0          alpha = max(val, alpha)
    12       477        314.0      0.7      0.0      return val
```

Nachher:
```
Total time: 32.3981 s
File: <ipython-input-8-421f54641f93>
Function: alphaBeta at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     1                                           def alphaBeta(s, p, limit, alpha, beta):
     2     10130   30232789.0   2984.5     93.3      nss = nextStates(s, p)
     3     10130     139398.0     13.8      0.4      if finished(s, p, ns=nss):
     4                                                   return utility(s, p)
     5     10130       8500.0      0.8      0.0      if limit == 0:
     6      8651    1940174.0    224.3      6.0          return heuristic(s, p)
     7      1479       1118.0      0.8      0.0      val = alpha
     8     11274      10124.0      0.9      0.0      for ns in nss:
     9     10811      38569.0      3.6      0.1          val = max(val, -value_AB(ns, opponent(p), limit-1, -beta, -alpha))
    10     10811      12106.0      1.1      0.0          if val >= beta:
    11      1016        951.0      0.9      0.0              return val
    12      9795      13995.0      1.4      0.0          alpha = max(val, alpha)
    13       463        327.0      0.7      0.0      return val
```

Auch dies gab einen kleinen Performance Boost. Bei Fragen können wir gerne nochmal über Discord diskutieren ;)

2021-02-09 21:30 UTC, nclskfm reviewed
:thinking: :thought_balloon: 

@benfu99 möchte bestimmt auch noch drüber schauen

2021-02-11 10:46 UTC, benfu99 requested changes

2021-02-11 10:46 UTC, benfu99 commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "    nss = nextStates(s, p)\n",
Die Variable würde ich anders benennen. Unter nss kann ich mir nicht wirklich was vorstellen^^

2021-02-11 10:48 UTC, jstsddg commented on jupyter/nmm-alpha-beta-pruning.ipynb
> +    "    nss = nextStates(s, p)\n",
Hast du eine Idee? :D Ich hatte leider keine bessere :(

2021-02-11 18:07 UTC, benfu99 approved these changes

2021-02-11 19:35 UTC, merged